### PR TITLE
[Enhancement] Update to use qb-target & Polyzone

### PR DESCRIPTION
**Pull request by FildonPrime**
- Switched Cab spawning logic (used vehicle spawning snippet from MojiaGarages) _Config contains all spawn locations_
- Added npc to interact 
- Converted and added all drop and pickup polyzones 
- Uses (qb-core-dev) DrawText

### CODE REVIEW

**Comment by DannysRP** [comment]
The option to park is a notify and not draw text. When peds leave the vehicle on drop off they don't close the door. Sometimes it takes a minute to recognize a drop off/pick up zone. You have to leave the zone and drive back in for draw text to pop up. Meter still shows after storing vehicle.

**Comment by FildonPrime** [comment]
@DannysRP 
- Switched the notify to DrawText 
- Fixed where the meter was showing after storing the vehicle. 
- _i couldnt replicate the issue with pickup/drop zones._  
- _NPC not closing the door properly, i was able to replicate this issue with "some" ped models, ill take a look at this further._

**Comment by DannysRP** [comment]
@FildonPrime It does it for me on the second run. Just did a fresh install and it works fine on the first pickup, If you go to do a second pickup the draw text does not show up when you first arrive to pick up/drop off the ped. You have to drive out of the zone and back into it for the draw text to show

**Comment by FildonPrime** [comment]
@DannysRP im finding it hard to replicate this issue though, did you directly tp on top of the blip / polyzone ? 
I just did a couple of runs and works fine. 
_Also please note that zone widths are not set to the full width of the road._

**Pull request merged**
