### PR TITLE
Fix incorrect calculation + Config.StartingPrice

### PR DESCRIPTION
**Pull request by Re1ease**
**Describe Pull request**
Fixes the incorrect calculation for price/distance.
Adds a feature that allows users to set a static starting price.

If your PR is to fix an issue mention that issue here
https://github.com/qbcore-framework/qb-taxijob/issues/51

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **yes**
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**

### CODE REVIEW

**Comment by Leslija** [comment]
So.. @tom-osborne 
The calculation now includes the default price from Config.Meter. 
BUT The **["startingPrice"]** is not needed, because it is nowhere to be seen? If someone uses another taximeter NUI where it is shown, that might be great.. Otherwise, confusion will increase...

Also.. His given price 125.0 is too high for an RP server?? I could understand that, because when calculating with lower prices, the total price is not updated with commas, but only in whole numbers.

However!! At the very beginning, it gives +$1 even driven 0 miles.
image
**And it happens to any given price..**
image

**Therefore, the calculation MUST contain -1 to avoid confusion!**
So the line should look like this: local fareAmount = ((meterData['distanceTraveled'])*Config.Meter["defaultPrice"])-1
And with the line the fix is correct. If you change ["defaultPrice"], the "Total Price" change almost exactly (including +0.1/-0.1 inaccuracy).

SS:
image

the +0.1/-0.1 inaccuracy
image

**Comment by Re1ease** [comment]
> The calculation now includes the default price from Config.Meter.
> BUT The ["startingPrice"] is not needed, because it is nowhere to be seen? If someone uses another taximeter NUI where it is shown, that might be great.. Otherwise, confusion will increase...

You can set it as 0 to not use it. 

> Also.. His given price 125.0 is too high for an RP server?? I could understand that, because when calculating with lower prices, the total price is not updated with commas, but only in whole numbers.

That's relative. You can also reduce it if you think it's too high. One mile is very far in GTA, FYI. 

> However!! At the very beginning, it gives +$1 even driven 0 miles.

I did another test, and this didn't happen to me. It could be if you slightly move your vehicle back or forward, it might add a dollar since it uses math.ceil().

**Comment by Leslija** [comment]
Agreed, but it's not like nopixel taximeter where you can see the base price. OK, you can leave it like that, maybe that's a good thing to have some updates....

The mile, right... True too! But for the price you can run and pay almost 30$ is a bit too much.... but that's up to the person changing the price.. so the option is to change it!

With the move, yes I moved a bit. It gives +$1 and then updates only in a while when the price starts to calculate. As a novice cab driver, I would be confused as to why this is.

Thanks and good job! I have some other bugs and will report them following.. [😅]

**Comment by tom-osborne** [comment]
@Re1ease How do you feel about switching to `math.floor` instead of `math.ceil` to eliminate that issue?

**Comment by tom-osborne** [comment]
@Leslija Thanks for the detailed feedback, much appreciated.

**Comment by Leslija** [comment]
Great, fixed 
image

Moving slight a bit..
image

**Review by tom-osborne — APPROVED** [review]

**Pull request merged**
